"""Change TokenTable

Revision ID: 526722deb8b9
Revises: 9cc6f97c4ac5
Create Date: 2023-12-27 12:51:45.714467

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526722deb8b9"
down_revision: Union[str, None] = "9cc6f97c4ac5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token", sa.Column("refresh_toke", sa.String(length=450), nullable=False)
    )
    op.create_unique_constraint(None, "token", ["refresh_toke"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "token", type_="unique")
    op.drop_column("token", "refresh_toke")
    # ### end Alembic commands ###
