"""Change TokenTable

Revision ID: 9cc6f97c4ac5
Revises: 27f666f79f3f
Create Date: 2023-12-27 12:17:25.212039

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cc6f97c4ac5"
down_revision: Union[str, None] = "27f666f79f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
